// <auto-generated />
using CarRentalManagementSystemAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalManagementSystemAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230516125723_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalManagementSystemAPI.Models.Car", b =>
                {
                    b.Property<string>("Car_No")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Boot_space")
                        .HasColumnType("int");

                    b.Property<float>("Charges_Per_Hour")
                        .HasColumnType("real");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Km_Driven")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sitting_Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year_Of_Manufacturing")
                        .HasColumnType("int");

                    b.HasKey("Car_No");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
